apiVersion: v1
kind: Pod
metadata:
  name: host-path
spec:
  containers:
  - image: alpine
    name: test-container
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
    - mountPath: /var/log/host
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /var/log
      # this field is optional
      type: Directory
