apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-auth
  namespace: keycloak
spec:
  secretName: keycloak-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - lab
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  commonName: keycloak.keycloak-auth.lab
  dnsNames:
    - keycloak.keycloak-auth.lab
  issuerRef:
    name: keycloak-ca-issuer
    kind: Issuer
